export const CREATE_PLAYLIST = "CREATE_PLAYLIST";
export const DELETE_PLAYLIST = "DELETE_PLAYLIST";
export const EDIT_PLAYLIST = "EDIT_PLAYLIST";
export const ADD_SONG_TO_PLAYLIST = "ADD_SONG_TO_PLAYLIST";
export const GET_USER_ID = "GET_USER_ID";
export const GET_USER_ID_ERROR = "GET_USER_ID_ERROR";
export default FETCH_PLAYLISTS = "FETCH_PLAYLISTS";